kind = "mobile"
previewPath = "/"
title = "NIKU - Nihongoku"
version = "1.0.0"
id = "artifacts/niku"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18968

[services.development]
run = "pnpm --filter @workspace/niku run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/niku", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/niku", "run", "serve" ]

[services.env]
PORT = "18968"
BASE_PATH = "/"
